// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-2t26qoKRJ7auM7tF3OzvOxGJJ5x-Mw',
    appId: '1:135333269617:web:ce2e1df50f1532057e0bd0',
    messagingSenderId: '135333269617',
    projectId: 'foodflow-78f01',
    authDomain: 'foodflow-78f01.firebaseapp.com',
    databaseURL: 'https://foodflow-78f01-default-rtdb.firebaseio.com',
    storageBucket: 'foodflow-78f01.firebasestorage.app',
    measurementId: 'G-6MWN8QWNE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVN_Rg_VTWtkPLe_1kZtQy1kk09LMAAiE',
    appId: '1:135333269617:android:e2bc59e8d9d25fa47e0bd0',
    messagingSenderId: '135333269617',
    projectId: 'foodflow-78f01',
    databaseURL: 'https://foodflow-78f01-default-rtdb.firebaseio.com',
    storageBucket: 'foodflow-78f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRhxjPx9ioPOyzhw7hsCd9WBqRfA7sJE',
    appId: '1:135333269617:ios:25af1068dd8b0d4e7e0bd0',
    messagingSenderId: '135333269617',
    projectId: 'foodflow-78f01',
    databaseURL: 'https://foodflow-78f01-default-rtdb.firebaseio.com',
    storageBucket: 'foodflow-78f01.firebasestorage.app',
    iosBundleId: 'com.example.foodFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRhxjPx9ioPOyzhw7hsCd9WBqRfA7sJE',
    appId: '1:135333269617:ios:25af1068dd8b0d4e7e0bd0',
    messagingSenderId: '135333269617',
    projectId: 'foodflow-78f01',
    databaseURL: 'https://foodflow-78f01-default-rtdb.firebaseio.com',
    storageBucket: 'foodflow-78f01.firebasestorage.app',
    iosBundleId: 'com.example.foodFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn-2t26qoKRJ7auM7tF3OzvOxGJJ5x-Mw',
    appId: '1:135333269617:web:8063770e98a45d327e0bd0',
    messagingSenderId: '135333269617',
    projectId: 'foodflow-78f01',
    authDomain: 'foodflow-78f01.firebaseapp.com',
    databaseURL: 'https://foodflow-78f01-default-rtdb.firebaseio.com',
    storageBucket: 'foodflow-78f01.firebasestorage.app',
    measurementId: 'G-FWGKRJWVJP',
  );

}